title: 'My simple notes'
description: 'The simplest way to keep my personal notes'
author: Purwo Widodo
github: https://github.com/purwowd
about: Software / Back-End Engineer with 2+ years of experience.
disqus_shortname: purwowd
google_analytics: UA-XXXXXXXX-Y
avatar_url: /static/img/avatar.jpeg
about_url: /static/img/about.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: bi-linkedin
      link: "https://www.linkedin.com/in/purwowd/"
    - icon: bi-envelope-open-fill
      link: "mailto:id.purwowd@gmail.com"
    - icon: bi-github
      link: "https://github.com/purwowd"
    - icon: bi-geo-alt-fill
      link: "https://goo.gl/maps/RevAYM3LQJHpPZ1S7"
    - icon: bi-whatsapp
      link: "http://wa.me/6287838311808"
    - icon: bi-twitter
      link: "https://twitter.com/purwowd"
    - icon: bi-facebook
      link: "https://fb.com/purwowd"
    - icon: bi-stack-overflow
      link: "https://stackoverflow.com/users/11934986"
    - icon: bi-telegram
      link: "https://t.me/purwowd"

share:
  twitter_username: github.io

urls:
    - text: About
      url: /about/
    - text: Contact
      url: /contact/
    # - text: My Projects
    #   url: /projects/
    - text: XML Feed
      url: /feed.xml

url: "https://purwowd.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-admin

jekyll_admin:
  homepage: "posts"
  hidden_links:
    - pages
    - staticfiles
    - datafiles

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
