title: 'My simple notes 👨🏻‍💻'
description: 'The simplest way to keep my personal notes'
author: Purwo Widodo
github: https://github.com/purwowd
about: I'm a software engineer in backend team. Especially on python / django.
disqus_shortname: purwowd
google_analytics: UA-XXXXXXXX-Y
avatar_url: /static/img/avatar.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/purwowd/"
    - icon: fa-envelope
      link: "mailto:id.purwowd@gmail.com"
    - icon: fa-github
      link: "https://github.com/purwowd"
    - icon: fa-street-view
      link: "https://goo.gl/maps/RevAYM3LQJHpPZ1S7"
    - icon: fa-whatsapp
      link: "http://wa.me/6287838311808"
    - icon: fa-twitter
      link: "https://twitter.com/purwowd"
    - icon: fa-stack-overflow
      link: "https://stackoverflow.com/users/11934986"

share:
  twitter_username: github.io

urls:
    - text: About
      url: /about/
    - text: Contact
      url: /contact/
    # - text: My Projects
    #   url: /projects/
    - text: XML Feed
      url: /feed.xml

url: "https://purwowd.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
